[[pages]]
path = "/"
screenshotTimestamp = "2026-06-06T12:39:12Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/3ea4d389-2e1f-4e47-a574-beda109d50ce/52d346d0-91de-41ba-8431-c897b778dc59/HxPjO72"
